### ISSUE TITLE
Update Extism Playground to Latest JS SDK

### ISSUE THREAD

**Issue by wikiwong** [extism/playground#20]
The Extism playground is currently broken: https://playground.extism.org/. Updating to the latest JS SDK should fix it

https://github.com/extism/playground

**Comment by neuronicnobody** [comment]
Waiting for js-sdk to land

**Comment by wikiwong** [comment]
JS SDK is available @ 1.0.0-rc5: https://www.npmjs.com/package/@extism/extism
