### ISSUE TITLE
playground couldn't load code.wasm

### ISSUE THREAD

**Issue by develop7** [extism/playground#25]
Steps to reproduce:

1. navigate https://playground.extism.org/

Expected: no error message

Instead: an error message, see screenshot below 

![image](https://github.com/extism/playground/assets/89889/d3eee618-e7d3-4cb6-8fac-61291b8f83f2)

<details>
<summary>Developer tools' console error message</summary>

```
XHROPTIONS
https://raw.githubusercontent.com/extism/extism/main/wasm/code.wasm
CORS Preflight Did Not Succeed
```

</details>

**Comment by bhelx** [comment]
Thank you, I think that default raw github url is no longer working. I'll deploy some of the test wasm files along with the app. In the meantime you should be able to ignore the error and load from disk.
